In [2]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(type(a))
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size:", a.size)
print("dtype", a.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
ndim: 2
shape: (2, 3)
size: 6
dtype int64


In [6]:
a = np.array([1, 2, 3], dtype="float64")
b = np.arange(10, 30, 5)
c = np.linspace(10, 30, 6)
print(a)
print(b)
print(c)

[1. 2. 3.]
[10 15 20 25]
[10. 14. 18. 22. 26. 30.]


In [7]:
a = np.zeros([2, 3])
b = np.ones([2, 3])
c = np.empty([2, 3])

print(a)
print(b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#np.random.seed(0)
a = np.random.rand(2, 3)
b = np.random.randn(2, 3)
c = np.random.randint(0, 10, 5)

print(a)
print(b)
print(c)

[[0.77834548 0.94957105 0.66252687]
 [0.01357164 0.6228461  0.67365963]]
[[-0.68658948  0.01487332 -0.3756659 ]
 [-0.03822364  0.36797447 -0.0447237 ]]
[7 2 9 2 3]


In [23]:
a = np.arange(0, 6)
b = a.reshape(2, 3)
c = a.reshape(6, -1)
print(a)
print(b)
print(c)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [26]:
a = np.arange(0, 100).reshape(10, 10)
print(a)
print(a[1])
print(a[1, 1])
print(a[1:5, 1:5])
print(a[:, 1])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[10 11 12 13 14 15 16 17 18 19]
11
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
[ 1 11 21 31 41 51 61 71 81 91]


In [27]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = 10
print(a + b)
print(a + c)
print(a.dot(b))

[11 22 33]
[11 12 13]
140


In [28]:
a = np.array([80, 60, 30, 70, 40])
print(a < 50)

a[a < 50] = 0
print(a)

[False False  True False  True]
[80 60  0 70  0]


In [29]:
a = np.array([50, 60, 80, 60, 50])
print(a)
print(np.sum(a))
print(np.average(a))
print(np.var(a))
print(np.std(a))

[50 60 80 60 50]
300
60.0
120.0
10.954451150103322
